# Generated by Django 2.2.6 on 2019-10-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barcode',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('m1', '중1'), ('m2', '중2'), ('m3', '중3'), ('h1', '고1'), ('h2', '고2'), ('h3', '고3'), ('t', '선생님')], default='m1', max_length=2),
        ),
    ]
