# Generated by Django 2.2.6 on 2019-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191006_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(choices=[('1', '1반'), ('2', '2반'), ('3', '3반'), ('4', '4반'), ('5', '5반'), ('6', '6반'), ('7', '7반'), ('8', '8반'), ('9', '9반'), ('10', '10반'), ('11', '11반'), ('12', '12반'), ('13', '13반'), ('14', '14반')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='홍길동', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studentno',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('h1', '고1'), ('h2', '고2'), ('h3', '고3'), ('t', '선생님')], default='h1', max_length=2),
        ),
    ]
