# Generated by Django 2.2.6 on 2019-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191031_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('1', '고1'), ('2', '고2'), ('3', '고3')], default='h1', max_length=2),
        ),
    ]
