# Generated by Django 2.2.6 on 2019-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191114_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='barcode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='1900-11-11', help_text='주민등록번호 앞 6자리 형태로 입역해주세요'),
            preserve_default=False,
        ),
    ]
