# Generated by Django 2.2.6 on 2019-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191117_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='1900-1-1'),
        ),
    ]
