# Generated by Django 2.2.6 on 2019-11-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191117_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='1900-1-1', help_text='1900-11-11 형태로 입력하세요'),
        ),
    ]
