FROM python:3.8.0rc1-slim-buster
RUN apt-get update && \
    apt-get install -y build-essential python

ADD . /medline
WORKDIR /medline

RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt
RUN pip install uwsgi
ENV PORT=8000
EXPOSE 8000
RUN chmod 755 /medline/runner.sh
CMD ["/medline/runner.sh"]