# Generated by Django 3.0.9 on 2020-08-14 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('message', models.TextField()),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('reserve_date', models.DateField(default=django.utils.timezone.now)),
                ('reserve_time', models.CharField(choices=[('아침시간', '아침시간'), ('1교시 후', '1교시 후'), ('2교시 후', '2교시 후'), ('3교시 후', '3교시 후'), ('4교시 후', '4교시 후'), ('5교시 후', '5교시 후'), ('점심시간', '점심시간'), ('6교시 후', '6교시 후'), ('7교시 후', '7교시 후')], default='1교시 후', max_length=15)),
                ('image', models.ImageField(blank=True, default='consult_image/notfound.png', upload_to='consult_image')),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a1', '복통'), ('a2', '외상'), ('a3', '두통'), ('a4', '어지로움')], max_length=300)),
                ('is_finished', models.BooleanField(default=False)),
                ('prescription_exists', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pills', models.SmallIntegerField(default=0)),
                ('schedule', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=300)),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medline.consult')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalhub.MedicineType')),
            ],
        ),
    ]
