# Generated by Django 2.2.6 on 2019-10-06 13:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='제목없음', max_length=100)),
                ('message', models.CharField(max_length=3000)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='consult_image/notfound.png', upload_to='consult_image')),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('a1', 'First Symptom'), ('a2', 'Second Symptom'), ('a3', 'Third Symptom'), ('a4', 'Fourth Symptom')], max_length=30)),
            ],
        ),
    ]
