# Generated by Django 2.2.6 on 2019-10-06 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0002_consult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='reserve_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
