# Generated by Django 2.2.6 on 2019-10-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0004_consult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='status',
        ),
    ]
