# Generated by Django 2.2.6 on 2019-10-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0005_remove_consult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
