# Generated by Django 2.2.6 on 2019-10-10 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0006_consult_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='reserve_datetime',
        ),
        migrations.AddField(
            model_name='consult',
            name='reserve_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='consult',
            name='reserve_time',
            field=models.TimeField(choices=[('08:05:00', '아침시간'), ('09:20:00', '1교시 후'), ('10:20:00', '2교시 후'), ('11:20:00', '3교시 후'), ('12:20:00', '4교시 후'), ('13:20:00', '5교시 후'), ('14:10:00', '점심시간'), ('15:10:00', '6교시 후'), ('16:10:00', '7교시 후')], default=datetime.datetime.now),
        ),
    ]
