# Generated by Django 2.2.6 on 2019-10-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0007_auto_20191010_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consult',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
