# Generated by Django 2.2.6 on 2019-10-16 02:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0008_auto_20191010_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='reserve_time',
            field=models.CharField(choices=[('bf', '아침시간'), ('a1', '1교시 후'), ('a2', '2교시 후'), ('a3', '3교시 후'), ('a4', '4교시 후'), ('a5', '5교시 후'), ('lu', '점심시간'), ('a6', '6교시 후'), ('a7', '7교시 후')], default='a1', max_length=2),
        ),
        migrations.AlterField(
            model_name='consult',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a1', '복통'), ('a2', '외상'), ('a3', '두통'), ('a4', '어지로움')], max_length=30),
        ),
    ]
