# Generated by Django 2.2.6 on 2019-11-04 09:09

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicalhub', '__first__'),
        ('medline', '0012_auto_20191031_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='schedule',
        ),
        migrations.AddField(
            model_name='prescription',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medline.consult'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a1', '복통'), ('a2', '외상'), ('a3', '두통'), ('a4', '어지로움')], max_length=300),
        ),
        migrations.AlterField(
            model_name='consult',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', '아침'), ('lunch', '점심'), ('dinner', '저녁')], max_length=300)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalhub.MedicineType')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medline.Prescription')),
            ],
        ),
    ]
