# Generated by Django 2.2.6 on 2019-11-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0018_auto_20191113_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medline.Prescription'),
        ),
    ]
