# Generated by Django 2.2.6 on 2019-11-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0020_auto_20191113_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='prescription',
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medline.consult'),
        ),
        migrations.DeleteModel(
            name='prescription',
        ),
    ]
