# Generated by Django 2.2.6 on 2019-11-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0021_auto_20191114_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedicine',
            name='number_of_pills',
            field=models.SmallIntegerField(default=0),
        ),
    ]
