# Generated by Django 2.2.6 on 2019-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0022_prescribedmedicine_number_of_pills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='reserve_time',
            field=models.CharField(choices=[('아침시간', '아침시간'), ('1교시 후', '1교시 후'), ('2교시 후', '2교시 후'), ('3교시 후', '3교시 후'), ('4교시 후', '4교시 후'), ('5교시 후', '5교시 후'), ('점심시간', '점심시간'), ('6교시 후', '6교시 후'), ('7교시 후', '7교시 후')], default='a1', max_length=2),
        ),
    ]
