# Generated by Django 2.2.6 on 2019-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0023_auto_20191117_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='reserve_time',
            field=models.CharField(choices=[('bf', '아침시간'), ('a1', '1교시 후'), ('a2', '2교시 후'), ('a3', '3교시 후'), ('a4', '4교시 후'), ('a5', '5교시 후'), ('lu', '점심시간'), ('a6', '6교시 후'), ('a7', '7교시 후')], default='a1', max_length=2),
        ),
    ]
