# Generated by Django 2.2.6 on 2019-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0024_auto_20191117_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='prescription_exists',
            field=models.BooleanField(default=False),
        ),
    ]
