# Generated by Django 2.2.6 on 2019-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medline', '0026_auto_20191117_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='reserve_time',
            field=models.CharField(choices=[('아침시간', '아침시간'), ('1교시 후', '1교시 후'), ('2교시 후', '2교시 후'), ('3교시 후', '3교시 후'), ('4교시 후', '4교시 후'), ('5교시 후', '5교시 후'), ('점심시간', '점심시간'), ('6교시 후', '6교시 후'), ('7교시 후', '7교시 후')], default='1교시 후', max_length=15),
        ),
    ]
